package(default_visibility = ["//visibility:public"])

cc_library(
  name = "algsort",
  srcs = [
    "algsort.cc",
  ],
  hdrs = [
    "algsort.h",
  ],
  deps = [
    "@com_github_glog_glog//:glog",
  ],
)