package(default_visibility = ["//visibility:public"])

cc_test(
  name = "test_sort",
  srcs = [
    "sort_test.cc",
  ],
  deps = [
    "//massive:algsort",
    "@com_google_googletest//:gtest_main",
    "@com_github_glog_glog//:glog"
  ],
)